name: neocloud_mobile_android
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  dio: ^5.9.2
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.3.1
  go_router: ^17.3.0
  mobile_scanner: ^7.2.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.2
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
